name: Dizadesign
favicon: null
layout_spectrum: 0.65076
typography_spectrum: 0.26774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#39424a'
    - '#679dcc'
    - '#b3cee6'
    - '#5e656b'
  brandStrength: 0.9637638700660318
  lightness: 0.005584777100011706
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
